# Generated by Django 3.2.9 on 2021-11-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedata',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
