# Generated by Django 3.2.9 on 2021-11-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0002_parsedata_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='parsedata',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_app.link'),
        ),
    ]
