# Generated by Django 3.2.9 on 2021-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0003_auto_20211103_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedata',
            name='link',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
