# Generated by Django 3.2.9 on 2021-11-04 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parse_app', '0004_auto_20211103_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedata',
            name='owner_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
