# Generated by Django 3.2.9 on 2021-11-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0005_parsedata_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsedata',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
