# Generated by Django 3.2.9 on 2021-11-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0006_rename_owner_id_parsedata_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedata',
            name='link',
        ),
    ]
