# Generated by Django 3.2.9 on 2021-11-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0007_remove_parsedata_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedata',
            name='price',
            field=models.FloatField(),
        ),
    ]
