# Generated by Django 3.2.9 on 2021-11-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0008_alter_parsedata_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedata',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
