# Generated by Django 3.2.9 on 2021-11-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0009_parsedata_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedata',
            name='owner',
        ),
    ]
