# Generated by Django 3.2.9 on 2021-11-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_app', '0010_remove_parsedata_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedata',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
